project:
  type: website
  resources:
    - "files/*"

website:
  title: "David Loeb"
  favicon: files/favicon.svg
  navbar:
    left:
      - research.qmd
      - software.qmd
      - teaching.qmd
      - href: cv.qmd
        text: "CV"
      # - blog.qmd  # removing for now
    search: false
  page-footer: 
    right: 'Built with [{{< iconify simple-icons quarto >}} Quarto](https://quarto.org){target="_blank"}<br>[View source on {{< iconify fa github >}} GitHub](https://github.com/david-loeb/david-loeb.github.io){target="_blank"}'
    background: light

format:
  html:
    theme:
      light: [flatly, style.scss]
      dark: [darkly, style.scss]
    respect-user-color-scheme: true
    include-after-body:
      text: |
        <script>
        document.addEventListener("DOMContentLoaded", () => {
          const homePageNavLink = document.querySelector(".navbar-brand");
          if (homePageNavLink.href === window.location.href) {
            homePageNavLink.classList.add("active");
          }
        });
        </script>
