---
title: "Teaching"
---

I have taught several research and programming workshops, served as a teaching assistant, and mentored education policy master's students.

## Workshops

### {{< iconify carbon data-analytics >}} [Missing Data Handling for Policy Research and RCTs](https://davidloeb.co/missing-data-wkshp/#/title-slide){target="_blank"}

A two-hour workshop conducted for the [University of Michigan Youth Policy Lab](https://youthpolicylab.umich.edu){target="_blank"} in May 2025. I provided a detailed demonstration of the performance of the major missing data handling strategies with a particular focus on the randomized controlled trial (RCT) setting. I explained how full information maximum likelihood (FIML) and mutliple imputation (MI) work and why they typically outperform other methods. However, I also showed why simpler methods will often perform just as well as FIML and MI in RCTs. None of these methods are perfect, and I ended with a demonstration of sensitivity analyses for violations of their core assumptions.

[View the workshop slides here](https://davidloeb.co/missing-data-wkshp/#/title-slide){target="_blank"}. R code that implements all of the methods discussed and the workshop slides source code are [available on {{< iconify fa github >}} GitHub](https://github.com/david-loeb/missing-data-wkshp){target="_blank"}.

### {{< iconify mdi language-r >}} [R Fundamentals](https://github.com/david-loeb/r-fundamentals-wkshp){target="_blank"}

An introduction to R from the ground up conducted for my research team of five master's students at the University of Pennsylvania in the winter and spring of 2024. We covered the basic building blocks of R; the creation of datasets by merging, cleaning and wrangling publicly avaialable data; reshaping data; simple descriptive analyses; and mapping. The materials are [available on {{< iconify fa github >}} GitHub](https://github.com/david-loeb/r-fundamentals-wkshp){target="_blank"}.

### {{< iconify fa-brands python >}} [Document Classification with Python](https://github.com/david-loeb/doc-classification-py-wkshp){target="_blank"}

A document classification demonstration in Python conducted for my master's student research team in the spring of 2024. We covered extracting text from PDFs and other documents into tabular text datasets, pre-processing the text, vectorizing, training a classification model with supervised learning, assessing model performance, and generating labels for all documents in the set. The materials are [available on {{< iconify fa github >}} GitHub](https://github.com/david-loeb/doc-classification-py-wkshp){target="_blank"}.

### {{< iconify fa-brands python >}} [Web Scraping with Python](https://davidloeb.co/web-scraping-py-wkshp/#/title-slide){target="_blank"}

An introduction to web scraping in Python conducted for a small group doctoral students in September 2023. [View the workshop slides here](https://davidloeb.co/web-scraping-py-wkshp/#/title-slide){target="_blank"}. A Python script with code for the workflow discussed and the workshop slides source code are [available on {{< iconify fa github >}} GitHub](https://github.com/david-loeb/web-scraping-py-wkshp){target="_blank"}.

## Courses

### Sociology of Education (EDUC 5782)

Teaching assistant for this master's level course at the University of Pennsylvania in the fall of 2024.

## Mentorship

I mentored a research team of five education policy master's students at the University of Pennsylvania during the winter and spring of 2024.